sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vikkasgupta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vikkasgupta/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-796165060835"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"