sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vikkasgupta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vikkasgupta/docker-react npm run test